# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MAKEFILE                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: crtorres <crtorres@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/09/18 14:52:05 by crtorres          #+#    #+#              #
#    Updated: 2022/09/18 17:01:07 by crtorres         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

CC = gcc
CCFLAGS = -Wall -Wextra -Werror

SRC = ft_atoi.c\
		ft_bzero.c\
		ft_calloc.c\
		ft_isalnum.c\
		ft_isalpha.c\
		ft_isascii.c\
		ft_isdigit.c\
		ft_isprint.c\
		ft_memchr.c\
		ft_memcmp.c\
		ft_memcpy.c\
		ft_memmove.c\
		ft_memset.c\
		ft_strchr.c\
		ft_strdup.c\
		ft_strlcat.c\
		ft_strlcpy.c\
		ft_strlen.c\
		ft_strncmp.c\
		ft_strnstr.c\
		ft_strrchr.c\
		ft_tolower.c\
		ft_toupper.c\
		ft_putchar_fd.c\
		ft_putstr_fd.c\
		

OBJS = $(SRC: .O)

INCLUDE = libft.h

$(NAME): $(OBJS) $(INCLUDE) 
	@ar rsc $(NAME) $(OBJS)

%.o : %.c 
	@$(CC) $(CCFLAGS) -c -o $@ $<

clean:
	@rm -f $(OBJS)

fclean:
	@rm -f $(OBJS)

re: all clean

.PHONY: all clean fclean re